export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./src/components/stitch-ui/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#d2bbff",
        "on-primary-fixed-variant": "#3323cc",
        "inverse-primary": "#c3c0ff",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#b8e0ff",
        "tertiary-container": "#006693",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#c3c0ff",
        "primary-container": "#4f46e5",
        "surface-bright": "#f7f9fb",
        "secondary-container": "#8a4cfc",
        "on-secondary-container": "#fffbff",
        "on-secondary": "#ffffff",
        "secondary-fixed": "#eaddff",
        "on-surface-variant": "#464555",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#004c6e",
        "surface-container-high": "#e6e8ea",
        "outline": "#777587",
        "outline-variant": "#c7c4d8",
        "on-primary-container": "#dad7ff",
        "surface-container-highest": "#e0e3e5",
        "on-error": "#ffffff",
        "surface-container": "#eceef0",
        "primary-fixed": "#e2dfff",
        "inverse-on-surface": "#eff1f3",
        "secondary": "#712ae2",
        "surface-dim": "#d8dadc",
        "tertiary": "#004d70",
        "tertiary-fixed": "#c9e6ff",
        "tertiary-fixed-dim": "#89ceff",
        "on-tertiary-fixed": "#001e2f",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#4d44e3",
        "surface": "#f7f9fb",
        "on-secondary-fixed": "#25005a",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        "on-primary-fixed": "#0f0069",
        "primary": "#3525cd",
        "on-surface": "#191c1e",
        "inverse-surface": "#2d3133",
        "background": "#f7f9fb",
        "on-secondary-fixed-variant": "#5a00c6",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
